version: 0.1
phases:
  pre_build:
    commands:
      - echo DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE} >> .env
      - echo DEV_DB_USER_NAME=${DEV_DB_USER_NAME} >> .env
      - echo DEV_DB_PASSWORD=${DEV_DB_PASSWORD} >> .env
      - echo DEV_DB_HOST=${DEV_DB_HOST} >> .env
      - echo DEV_DB_DATABASE_NAME=${DEV_DB_DATABASE_NAME} >> .env
      - echo DEV_DB_PORT=${DEV_DB_PORT} >> .env
      - echo DEV_DB_REGION=${DEV_DB_REGION} >> .env
      - echo ENVIROMENT=${ENVIROMENT} >> .env
      - echo DEBUG=${DEBUG} >> .env
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Building the application
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
