name: Run Test Cases

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      - name: Run Test Cases
        run: |
          python -m pip install -r requirements.txt
          python manage.py test