name: Run Precommits and Test Cases

on: [push, pull_request]

jobs:
  run-precommits-and-test-cases:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Run Precommits and Test Cases
        run: |
          python -m pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
        env:
          DEV_DB_USER_NAME: ${{ secrets.DEV_DB_USER_NAME }}
          DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
          DEV_DB_HOST: ${{ secrets.DEV_DB_HOST }}
          DEV_DB_DATABASE_NAME: ${{ secrets.DEV_DB_DATABASE_NAME }}
          DEV_DB_PORT: ${{ secrets.DEV_DB_PORT }}
          DEV_DB_REGION: ${{ secrets.DEV_DB_REGION }}
          ENVIROMENT: ${{ secrets.ENVIROMENT }}
