name: Check For DB Instances

on:
  push:
    branches: ['*' ,main, dev, stage, qa]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Run DB Scripts
        run: |
          python -m pip install -r requirement_db.txt
          python database/createUser.py
        env:
          DEV_DB_USER_NAME: ${{ secrets.DEV_DB_USER_NAME }}
          DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
          DEV_DB_HOST: ${{ secrets.DEV_DB_HOST }}
          DEV_DB_DATABASE_NAME: ${{ secrets.DEV_DB_DATABASE_NAME }}
          ENVIROMENT: ${{ secrets.ENVIROMENT }}